version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/jiangmiao/addrgen
    steps:
      - checkout
      - run:
          command: |
            sh test.sh
            go install
