version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/jiangmiao/addrgen
    steps:
      - checkout
      - run:
          command: |
            go get github.com/golang/dep/cmd/dep
            dep ensure
            sh test.sh
            go install
